version: '3'
services:
  application:
    image: royvanewater/trading-post:v1.0.0
    env_file: './config/trading-post.env'
    ports:
      - "80:80"
    deploy:
      replicas: 2
    networks:
      - trading-post
  mongo:
    image: mongo
    volumes:
      - ./config/mongo-data:/data/db
    networks:
      - trading-post
networks:
  trading-post:
