version: '3'
services:
  application:
    image: royvandewater/trading-post:v1.0.2
    env_file: './config/trading-post.env'
    deploy:
      replicas: 2
    networks:
      - trading-post
  mongo:
    image: mongo
    volumes:
      - ./config/mongo-data:/data/db
    networks:
      - trading-post
  traefik:
    image: traefik
    command: ["--docker","--docker.swarmmode","--docker.swarmmode=trading-post.club","--docker.watch","--web"]
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./config/traefik/acme.json:/etc/traefik/acme/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8181:8181"
    networks:
      - trading-post
networks:
  trading-post:
